# ========== STUB MODE (NO DB) ==========
# ========== STUB MODE (NO DB) ==========
app.store=stub

# Disable DB / JPA / Flyway in Spring Boot 4
spring.autoconfigure.exclude=\
org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,\
org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration,\
org.springframework.boot.flyway.autoconfigure.FlywayAutoConfiguration

# Disable DB / JPA / Flyway in Spring Boot 4
spring.autoconfigure.exclude=\
org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,\
org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration,\
org.springframework.boot.flyway.autoconfigure.FlywayAutoConfiguration

spring.flyway.enabled=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
logging.level.org.flywaydb=OFF
>>>>>>> ce458fa0d0d24d552fa5aa64ce13bd1eaa7700bc
